version: '2'

services:
  vpn:
    container_name: transmission_vpn
    image: danisla/openvpn-client:v1.0.0
    restart: always
    stop_signal: SIGKILL
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: bridge
    volumes:
      - "./vpn:/vpn"
    env_file: .env
    command: -f -t $$OVPN_TZ sg vpn -c "openvpn --config $$OVPN_CONFIG"

  transmission:
    container_name: transmission
    build: ./transmission/
    restart: always
    network_mode: "service:vpn"
    environment:
      USERID: 1000
      GROUPID: 1000
      RPC_URL: "/transmission/"
    volumes:
      - "./data:/var/lib/transmission-daemon/info"
      - "./complete:/var/lib/transmission-daemon/downloads"
      - "./downloading:/var/lib/transmission-daemon/downloading"
      - "./incomplete:/var/lib/transmission-daemon/incomplete"

  ipcheck:
    container_name: transmission_ipcheck
    build: ./ipcheck/
    network_mode: "service:vpn"

  router:
    container_name: transmission_router
    image: httpd:2.4
    network_mode: bridge
    links:
      - "transmission"
      - "ipcheck"
    ports:
      - "9091:80"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
